[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  from = "/auth"
  from = "/registration"
  from = "/profile"
  from = "/change-user-data"
  from = "/change-password"
  from = "/chat"
  from = "/404"
  from = "/500"
  to = "/index.html"
  status = 200